// priority: 0

onEvent('block.registry', event => {

	event.create('statue_roboss')
	.material('metal')
	.hardness(1.0)
	.displayName('Statue of R0B0TB0SS')
	.renderType('cutout')
	.notSolid()
	.lightLevel(0.5)
	.box(3,0,3,13,21,13, true)

	event.create('statue_kikongin')
	.material('metal')
	.hardness(1.0)
	.displayName('Statue of Kikongin')
	.renderType('cutout')
	.notSolid()
	.lightLevel(0.5)
	.box(3,0,3,13,21,13, true)

	event.create('statue_laimx')
	.material('metal')
	.hardness(1.0)
	.displayName('Statue of Laimx')
	.renderType('cutout')
	.notSolid()
	.lightLevel(0.5)
	.box(3,0,3,13,21,13, true)

	event.create('statue_blakdestroyer')
	.material('metal')
	.hardness(1.0)
	.displayName('Statue of Blakdestroyer')
	.renderType('cutout')
	.notSolid()
	.lightLevel(0.5)
	.box(3,0,3,13,21,13, true)
})