onEvent('block.registry', event => {
  event.create('resourcefulbees_trophy').material('rock').hardness(1).displayName('Resourcefulbees Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('ae2_trophy').material('rock').hardness(1).displayName('Applied Energistic 2 Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('mahoutsukai_trophy').material('rock').hardness(1).displayName('Mahou Tsukai Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('astralsorcery_trophy').material('rock').hardness(1).displayName('Astral Sorcery Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('rats_trophy').material('rock').hardness(1).displayName('Rats Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('twilightforest_trophy').material('rock').hardness(1).displayName('Twilight Forest Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('create_trophy').material('rock').hardness(1).displayName('Create Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('industrialforegoing_trophy').material('rock').hardness(1).displayName('Industrial Foregoing Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('mekanism_trophy').material('rock').hardness(1).displayName('Mekanism Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('thermal_trophy').material('rock').hardness(1).displayName('Thermal Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('extendedcrafting_trophy').material('rock').hardness(1).displayName('Extended Crafting Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('miscellaneous_trophy').material('rock').hardness(1).displayName('Miscellaneous Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('draconicevolution_trophy').material('rock').hardness(1).displayName('Draconic Evolution Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('botania_trophy').material('rock').hardness(1).displayName('Botania Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('powergen_trophy').material('rock').hardness(1).displayName('PowerGen Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('rftools_trophy').material('rock').hardness(1).displayName('RFTools Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
  event.create('projecte_trophy').material('rock').hardness(1).displayName('ProjectE Trophy').notSolid().renderType('cutout').defaultTranslucent().redstoneConductor(false)
})